# <span style="color:darkblue"> QTM 151 - Quiz 3 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your name below

In [1]:
# Write your answer here

print("Winnie Lau")

Winnie Lau

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [2]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [3]:
# Write your answer here

import numpy as np
import pandas as pd


<font size = "5">

(a) Replace the values of a column

<font size = "3">

- Import the "data_raw/constructors.csv" file
- Replace the values "British", "Japanese", and "Irish" with <br>
"UK", "Japan", "Ireland" in the column "nationality"


HINT: See the example in Lecture 12

In [5]:
# Write your own code

constructors = pd.read_csv("data_raw/constructors.csv")

list_old = ['British', 'Japanese', 'Irish']
list_new = ['UK', 'Japan', 'Ireland']

constructors["nationality"] = constructors["nationality"].replace(list_old, list_new)

<font size = "5">

(b) Aggregate and query

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Subset the observations for 'constructorId == 3' using ```.query()```
- Obtain the maximum of "laps" by "driverId" <br> 
 using ``` .groupby().agg() ```
- Subset the drivers with a maximum of laps $\ge 10$
- Store the results of all these operations in a dataframe <br>
```sprint_results_agg ```

In [17]:
# Write your own code

sprint = pd.read_csv("data_raw/sprint_results.csv")

sprint_results_laps = (sprint.query("constructorId == 3")
                      .groupby("driverId")
                      .agg(max_laps = ("laps", "max")))

sprint_results_agg = sprint_results_laps.query("max_laps >= 10")
display(sprint_results_agg)

          max_laps
driverId
847             24
848             23
849             24

<font size = "5">

(c) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1980-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [ ]:
# Write your own code

races = pd.read_csv("data_raw/races.csv")

bins1 = [1950, 1965, 1980, 2024]
labels1 = ["1950-1965","1966-1980","1981-onwards"]

races["year_brackets"] = pd.cut(races["year"],
                                bins=bins1,
                                right=True,
                                labels = labels1)

# correction:
# bins1 = [1949, 1965, 1980, float("inf")]
# bc the left bracket is not inclusive in pd.cut

<font size = "5">

(d) Aggregate and sort

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Obtain the maximum of "laps" by "driverId" <br> 
using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the maximum of laps using ``` .sort_values() ```

In [22]:
# Write your own code

sprint2 = pd.read_csv("data_raw/sprint_results.csv")

laps_agg = (sprint2.groupby("driverId")
            .agg(maximum_laps = ("laps", "max"))
            .sort_values(by="maximum_laps", ascending=False))

laps_agg

          maximum_laps
driverId
1                   24
4                   24
854                 24
853                 24
852                 24
849                 24
847                 24
846                 24
844                 24
842                 24
841                 24
840                 24
839                 24
832                 24
830                 24
825                 24
822                 24
817                 24
815                 24
20                  24
8                   24
855                 24
848                 23
9                   18

<font size = "5">

(e) Rename column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Rename the column "time" to "time_unformatted"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>
See Lecture 15

In [25]:
# Write your own code

sprint3 = pd.read_csv("data_raw/sprint_results.csv")

sprint3 = sprint3.rename(columns={'time':'time_unformatted'})
display(sprint3)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31

<font size = "5">

(f) Merge dataset

<font size = "3">

- Import the "data_raw/sprint_results.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"sprint_results" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "nationality" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [27]:
# Write your own code

sprint4 = pd.read_csv("data_raw/sprint_results.csv")
constructors2 = pd.read_csv("data_raw/constructors.csv")

sc_merge = pd.merge(sprint4,
                    constructors2[["nationality", "constructorId"]],
                    on = "constructorId",
                    how = "left")

sc_merge

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,British
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,British
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,French
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,French
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,British
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,British